import REQUIRE_LOGIN_PAGE_ID from './REQUIRE_LOGIN_PAGE_ID';
import NOT_REQUIRE_LOGIN_PAGE_ID from './NOT_REQUIRE_LOGIN_PAGE_ID';

// 页面的路由，用于在 React-Router 中使用
export default {
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_LIST]: '/insuranceList',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_PUBLICATION]: '/insurancePublication',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_PROCESS]: '/directPaymentProcess',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_DETAIL]: '/directPaymentDetail',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_PROCESS]: '/insurancePurchasingProcess',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_DETAIL]: '/insurancePurchasingDetail',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_PERSONAL_CENTER]: '/personalCenter',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_DETAIL]: '/insuranceDetail',
    [NOT_REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_LOGIN]: '/login',
    [NOT_REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_SIGN_UP]: '/signUp',
    [REQUIRE_LOGIN_PAGE_ID.INSURANCE_COMPANY_PERSONAL_INSURANCE_POLICY_FILLING]: '/insurancePolicyFilling',
};