// 页面的 ID，目前设想用于识别当前所在页面
export default {
    INSURANCE_COMPANY_PERSONAL_INSURANCE_LIST: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_LIST'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_PUBLICATION: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_PUBLICATION'),
    INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_PROCESS: Symbol('INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_PROCESS'),
    INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_DETAIL: Symbol('INSURANCE_COMPANY_PERSONAL_DIRECT_PAYMENT_DETAIL'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_PROCESS: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_PROCESS'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_DETAIL: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_PURCHASING_DETAIL'),
    INSURANCE_COMPANY_PERSONAL_PERSONAL_CENTER: Symbol('INSURANCE_COMPANY_PERSONAL_PERSONAL_CENTER'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_DETAIL: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_DETAIL'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_POLICY_FILLING: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_POLICY_FILLING'),
    INSURANCE_COMPANY_PERSONAL_INSURANCE_CLAUSE: Symbol('INSURANCE_COMPANY_PERSONAL_INSURANCE_CLAUSE'),
};